nz:
  - email
  - username
  - password
  - secret_question
  - answer_to_secret_question

  - application_id

  - family_name
  - given_name_1
  - given_name_2
  - given_name_3
  - other_names
  - title
  - other_title
  - gender
  - date_of_birth
  - country

  - street_number
  - address_1
  - suburb
  - city
  - province_state
  - postal_code

  - phone_number
  - phone_number_night
  - phone_number_mobile
  - fax_number

  - passport_number
  - passport_expiry_date
  - other_identification
  - other_issue_date
  - other_expiry_date

  - industry
  - occupation

  - renal_dialysis
  - tuberculosis
  - cancer
  - heart_disease
  - disability
  - hospitalisation
  - residential_care
  - pregnancy_status
  - health_details
  - tb_risk

  - imprisonment_5_years
  - imprisonment_12_months
  - removal_order
  - deported
  - deported_date
  - deported_country
  - charged
  - convicted
  - under_investigation
  - excluded
  - removed
  - exclude_removed_details

  - sufficient_funds_holiday
  - intended_travel_date
  - intended_leave_date
  - length_of_stay
  - been_to_nz
  - when_in_nz
  - previous_whs_permit_visa
  - previous_sfv_permit_visa