---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: '1'
  domain: yimin101.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  instance_id: i-fc1de523
  image_type: t1.micro
  image_id: ami-9b0b62a1
  security_groups:
  - default
  external_host: ec2-54-206-94-206.ap-southeast-2.compute.amazonaws.com
  external_ip: 54.206.94.206
  internal_host: ip-172-31-8-127.ap-southeast-2.compute.internal
  internal_ip: 172.31.8.127
  zone: ap-southeast-2b
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
